-- M1 schema: teams + matches. See docs/architecture.md §4.
-- Migrations are applied idempotently on boot inside a transaction.

CREATE TABLE IF NOT EXISTS teams (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fifa_id     TEXT UNIQUE,
    name        TEXT        NOT NULL,
    code        TEXT,
    flag_url    TEXT,
    group_label TEXT
);

CREATE TABLE IF NOT EXISTS matches (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fifa_id         TEXT UNIQUE,
    stage           TEXT        NOT NULL CHECK (stage IN ('group', 'r32', 'r16', 'qf', 'sf', 'final', 'third')),
    group_label     TEXT,
    match_number    INTEGER,
    home_team_id    BIGINT      REFERENCES teams (id),
    away_team_id    BIGINT      REFERENCES teams (id),
    kickoff_at      TIMESTAMPTZ,
    status          TEXT        NOT NULL DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'live', 'finished')),
    home_score      INTEGER,
    away_score      INTEGER,
    venue_stadium   TEXT,
    venue_city      TEXT,
    venue_country   TEXT,
    placeholder_home TEXT,
    placeholder_away TEXT,
    result_source   TEXT        NOT NULL DEFAULT 'fifa',
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_matches_kickoff_at ON matches (kickoff_at);
CREATE INDEX IF NOT EXISTS idx_matches_stage ON matches (stage);
CREATE INDEX IF NOT EXISTS idx_teams_group_label ON teams (group_label);
