-- 0011: multi-edition support, phase 1 — the tournaments entity + scoping columns
-- (ADR-0022). PURELY ADDITIVE and non-breaking:
--   * introduces `tournaments` and seeds the current edition (WC2026) as active;
--   * adds `tournament_id` to each per-edition table, backfilled to WC2026;
--   * a STABLE `active_tournament_id()` function is the column DEFAULT, so existing
--     INSERTs that don't yet set tournament_id route new rows to the ACTIVE edition
--     — the app keeps working unchanged until the query layer is made edition-aware.
-- Existing UNIQUE constraints are deliberately LEFT AS-IS here: several upserts use
-- ON CONFLICT (fifa_id)/(user_id,kind), so the edition-qualified uniques are swapped
-- in phase 2 together with those ON CONFLICT clauses. Applied idempotently on boot
-- inside a transaction.

CREATE TABLE IF NOT EXISTS tournaments (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       TEXT        NOT NULL UNIQUE,   -- e.g. 'WC2026', 'WC2030'
    name       TEXT        NOT NULL,          -- 'FIFA World Cup 2026'
    year       INTEGER     NOT NULL,
    is_active  BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- At most one edition may be active at a time.
CREATE UNIQUE INDEX IF NOT EXISTS uq_tournaments_active ON tournaments (is_active) WHERE is_active;

-- Seed the current edition and make it active (idempotent).
INSERT INTO tournaments (code, name, year, is_active)
VALUES ('WC2026', 'FIFA World Cup 2026', 2026, TRUE)
ON CONFLICT (code) DO NOTHING;

-- The active edition id — used as a transitional column DEFAULT so existing
-- INSERTs (which don't set tournament_id yet) route to the active edition.
CREATE OR REPLACE FUNCTION active_tournament_id() RETURNS BIGINT
LANGUAGE sql STABLE AS $$ SELECT id FROM tournaments WHERE is_active LIMIT 1 $$;

-- Helper block: add tournament_id, backfill to WC2026, enforce NOT NULL, default
-- to the active edition. Kept explicit per table (idempotent via IF NOT EXISTS).

-- teams
ALTER TABLE teams ADD COLUMN IF NOT EXISTS tournament_id BIGINT REFERENCES tournaments (id);
UPDATE teams SET tournament_id = (SELECT id FROM tournaments WHERE code = 'WC2026') WHERE tournament_id IS NULL;
ALTER TABLE teams ALTER COLUMN tournament_id SET NOT NULL;
ALTER TABLE teams ALTER COLUMN tournament_id SET DEFAULT active_tournament_id();
CREATE INDEX IF NOT EXISTS idx_teams_tournament ON teams (tournament_id);

-- matches
ALTER TABLE matches ADD COLUMN IF NOT EXISTS tournament_id BIGINT REFERENCES tournaments (id);
UPDATE matches SET tournament_id = (SELECT id FROM tournaments WHERE code = 'WC2026') WHERE tournament_id IS NULL;
ALTER TABLE matches ALTER COLUMN tournament_id SET NOT NULL;
ALTER TABLE matches ALTER COLUMN tournament_id SET DEFAULT active_tournament_id();
CREATE INDEX IF NOT EXISTS idx_matches_tournament ON matches (tournament_id);

-- tournament_picks
ALTER TABLE tournament_picks ADD COLUMN IF NOT EXISTS tournament_id BIGINT REFERENCES tournaments (id);
UPDATE tournament_picks SET tournament_id = (SELECT id FROM tournaments WHERE code = 'WC2026') WHERE tournament_id IS NULL;
ALTER TABLE tournament_picks ALTER COLUMN tournament_id SET NOT NULL;
ALTER TABLE tournament_picks ALTER COLUMN tournament_id SET DEFAULT active_tournament_id();
CREATE INDEX IF NOT EXISTS idx_tournament_picks_tournament ON tournament_picks (tournament_id);

-- bonus_rules
ALTER TABLE bonus_rules ADD COLUMN IF NOT EXISTS tournament_id BIGINT REFERENCES tournaments (id);
UPDATE bonus_rules SET tournament_id = (SELECT id FROM tournaments WHERE code = 'WC2026') WHERE tournament_id IS NULL;
ALTER TABLE bonus_rules ALTER COLUMN tournament_id SET NOT NULL;
ALTER TABLE bonus_rules ALTER COLUMN tournament_id SET DEFAULT active_tournament_id();

-- champion_tiers
ALTER TABLE champion_tiers ADD COLUMN IF NOT EXISTS tournament_id BIGINT REFERENCES tournaments (id);
UPDATE champion_tiers SET tournament_id = (SELECT id FROM tournaments WHERE code = 'WC2026') WHERE tournament_id IS NULL;
ALTER TABLE champion_tiers ALTER COLUMN tournament_id SET NOT NULL;
ALTER TABLE champion_tiers ALTER COLUMN tournament_id SET DEFAULT active_tournament_id();

-- audit_log (per-edition feed; existing rows are all WC2026-era)
ALTER TABLE audit_log ADD COLUMN IF NOT EXISTS tournament_id BIGINT REFERENCES tournaments (id);
UPDATE audit_log SET tournament_id = (SELECT id FROM tournaments WHERE code = 'WC2026') WHERE tournament_id IS NULL;
ALTER TABLE audit_log ALTER COLUMN tournament_id SET NOT NULL;
ALTER TABLE audit_log ALTER COLUMN tournament_id SET DEFAULT active_tournament_id();
CREATE INDEX IF NOT EXISTS idx_audit_tournament ON audit_log (tournament_id);

-- NOTE: predictions/points are NOT given their own tournament_id — a prediction's
-- edition is definitionally its match's edition (predictions.match_id ->
-- matches.tournament_id), so phase 2 scopes them via the matches join rather than
-- denormalizing (avoids drift).
