#!/usr/bin/env node
// Single battery runner — executes the verification pyramid and writes ONE
// committed evidence report (docs/qa/automated-verification-latest.md): proof,
// not claims. On-demand (`make qa`); CI remains the enforcing gate.
import { execSync } from 'node:child_process'
import { writeFileSync } from 'node:fs'

const STEPS = [
  ['gofmt', "test -z \"$(gofmt -l .)\"", 'backend'],
  ['go vet', 'go vet ./...', 'backend'],
  ['go test (unit+integration)', 'go test ./...', 'backend'],
  ['scoring evals', 'go test -tags=evals ./internal/scoring/', 'backend'],
  ['frontend build (tsc+vite)', 'npm run build', 'frontend'],
  ['frontend vitest', 'npm test', 'frontend'],
  ['mcp typecheck', 'npm run typecheck', 'mcp'],
  ['mcp evals', 'npm run eval', 'mcp'],
  ['traceability --check', 'node scripts/gen-traceability.mjs --check', '.'],
  ['eval ratchet', 'node scripts/check-eval-ratchet.mjs --check', '.'],
]

const results = []
for (const [name, cmd, cwd] of STEPS) {
  const t0 = Date.now()
  let ok = true
  try {
    execSync(cmd, { cwd, stdio: 'pipe' })
  } catch {
    ok = false
  }
  results.push({ name, ok, ms: Date.now() - t0 })
  console.log(`${ok ? '✓' : '✗'} ${name} (${results.at(-1).ms}ms)`)
}

const pass = results.filter((r) => r.ok).length
const stamp = new Date().toISOString()
const md = [
  '# Automated verification — latest run',
  '',
  `> Generated by \`scripts/qa-verify.mjs\` (\`make qa\`). Run at **${stamp}**.`,
  `> **${pass}/${results.length} gates passed.**`,
  '',
  '| Gate | Result | ms |',
  '|------|--------|----|',
  ...results.map((r) => `| ${r.name} | ${r.ok ? '✅ pass' : '❌ FAIL'} | ${r.ms} |`),
  '',
].join('\n')
writeFileSync('docs/qa/automated-verification-latest.md', md + '\n')
console.log(`\n${pass}/${results.length} passed → docs/qa/automated-verification-latest.md`)
process.exit(pass === results.length ? 0 : 1)
